    
    
    - name: Install Steam
      win_chocolatey:
        name: steam
        state: present
    - name: Install teamviewer 
      win_chocolatey:
        name: teamviewer
        state: present
    - name: Install spotify 
      win_chocolatey:
       name: spotify
       state: present
    - name: Install awscli 
      win_chocolatey:
       name: awscli
       state: present
    - name: Install vagrant 
      win_chocolatey:
       name: vagrant
       state: present
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result

    # output results
    - debug: var=result
    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required

    - name: Install win 10 linux subsystem 
      win_shell: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
