---
- name: Windows Build and config 
  hosts: all
  tasks:
  #list of common apps
    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        state: present
    - name: Install Adobe Reader
      win_chocolatey:
        name: adobereader
        state: present
    - name: Install WinRar
      win_chocolatey:
        name: winrar
        state: present
    - name: Install git
      win_chocolatey:
        name: git
        state: present
    - name: Install NotePad++
      win_chocolatey:
        name: notepadplusplus.install
        state: present
    - name: Install putty 
      win_chocolatey:
        name: putty
        state: present
    - name: Install Python3
      win_chocolatey:
        name: python3
        state: present
    - name: Install Python2
      win_chocolatey:
        name: python2
        state: present
    - name: Install Filezilla
      win_chocolatey:
        name: filezilla
        state: present    
    - name: Install MobaXTerm 
      win_chocolatey:
        name: mobaxterm
        state: present    
    - name: Install Dropbox 
      win_chocolatey:
        name: dropbox
        state: present   
    - name: Install Google Backup and Sync 
      win_chocolatey:
        name: google-backup-and-sync
        state: present     
    - name: Install Steam
      win_chocolatey:
        name: steam
        state: present
    - name: Install teamviewer 
      win_chocolatey:
        name: teamviewer
        state: present
    - name: Install spotify 
      win_chocolatey:
       name: spotify
       state: present
    - name: Install awscli 
      win_chocolatey:
       name: awscli
       state: present
    - name: Install vagrant 
      win_chocolatey:
       name: vagrant
       state: present
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result

    # output results
    - debug: var=result
    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required

    - name: Install win 10 linux subsystem 
      win_shell: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
