---
- hosts: all
  tasks:
  - name: Test system connection
    wait_for_connection:
      timeout: 20
    tags: backup 
  
  - name: Backup Agency Pro 
    win_robocopy:
      src: \\ispserv-apps\Apps$\Apro
      dest: \\ispserv\t-drive\Agency_Pro_Backup
      recurse: yes
      flags: /e /mir /np 
    return: msg
