---
- name:  Windows Update
  hosts: windows
  gather_facts: false
  tasks:
    - name: Perfoming updates on {{ inventory_hostname }}
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        state: installed
        log_path: C:\win-updates.txt
    
    - name: Send Windows Patched Notification to Teams
      win_shell: |
        $uri = 'https://outlook.office.com/webhook/'
        $body = ConvertTo-JSON @{
            text = ' Windows Updates installed on {{ inventory_hostname }} check logs on C:\ drive'
        }
        Invoke-RestMethod -uri $uri -Method Post -body $body -ContentType 'application/json'
    
    - name: 3rd party patching on {{ inventory_hostname }}
      win_chocolatey:
        name: all
        state: latest

    - name: Send Windows Patched Notification to Teams
      win_shell: |
        $uri = 'https://outlook.office.com/webhook/'
        $body = ConvertTo-JSON @{
            text = ' Third Party Updates installed on {{ inventory_hostname }} check logs on C:\ drive'
        }
        Invoke-RestMethod -uri $uri -Method Post -body $body -ContentType 'application/json'
